apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - /gitops-dev/backend-java/base
namePrefix: prd-
images:
  - name: eduazureregistry.azurecr.io/backend-java
    newTag: $TAG

commonLabels:
  app: backend-java
  environment: prd

