apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
namePrefix: dev-
images:
  - name: eduazureregistry.azurecr.io/frontend-vue
    newTag: main-20240718093150

commonLabels:
  app: frontend-vue
  environment: dev
