apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
namePrefix: prd-
images:
  - name: eduazureregistry.azurecr.io/backend-java
    newTag: 1.1.0

commonLabels:
  app: backend-java
  environment: prd
