apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
namePrefix: dev-
images:
  - name: eduazureregistry.azurecr.io/backend-java
    newTag: 1.1.0-20240719060142
  
  
commonLabels:
  app: backend-java
  environment: dev
