name: Branch and Tag Operations

on:
  workflow_dispatch:
    inputs:
      operation:
        description: 'Select operation (list-branches or list-tags)'
        required: true
        default: 'list-branches'
        type: choice
        options:
          - list-branches
          - list-tags

jobs:
  branch-tag-operations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Perform selected operation
        run: |
          if [ "${{ github.event.inputs.operation }}" == "list-branches" ]; then
            git fetch --all
            git branch -r | grep -v '\->' | sed 's/origin\///' > branches.txt
            echo "Branches:"
            cat branches.txt
          elif [ "${{ github.event.inputs.operation }}" == "list-tags" ]; then
            git fetch --all --tags
            git tag > tags.txt
            echo "Tags:"
            cat tags.txt
          fi

      - name: Upload results as artifacts
        if: ${{ github.event.inputs.operation == 'list-branches' || github.event.inputs.operation == 'list-tags' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.operation }}-results
          path: |
            branches.txt
            tags.txt
          if-no-files-found: ignore
