name: Prd Gitops Setting

on:
  workflow_dispatch:
    inputs:
      milestone:
        description: 'prd-milestone'
        required: true
        default: 'milestone 입력'
      backend-java-tag:
        description: 'backend-java tag'
        required: true
        default: 'backend-java tag 입력'
      frontend-vue-tag:
        description: 'frontend-vue tag'
        required: true
        default: 'frontend-vue tag 입력'

jobs:
  fetch-tags-and-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Fetch tags and branches
      - name: Fetch tags and branches
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git fetch --depth=1 origin +refs/heads/*:refs/heads/*

      # Check backend-java tag
      - name: Check backend-java tag
        run: |
          backend_java_tag="${{ github.event.inputs.backend-java-tag }}"

          if ! git tag -l | grep -q "^${backend_java_tag}$"; then
            echo "::error::Backend Java tag '${backend_java_tag}' does not exist in the repository"
            exit 1
          fi

      # Check frontend-vue tag
      - name: Check frontend-vue tag
        run: |
          frontend_vue_tag="${{ github.event.inputs.frontend-vue-tag }}"

          if ! git tag -l | grep -q "^${frontend_vue_tag}$"; then
            echo "::error::Frontend Vue tag '${frontend_vue_tag}' does not exist in the repository"
            exit 1
          fi

      # Check prd-milestone
      - name: Check prd-milestone
        run: |
          prd_milestone="${{ github.event.inputs.milestone }}"

          if ! git show-ref --tags | grep -q "/refs/tags/${prd_milestone}$"; then
            echo "::error::PRD milestone '${prd_milestone}' does not exist in the repository"
            exit 1
          fi
