name: Prd Gitops Setting

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Choose a tag to run'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: List tags
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git tag -l

      - name: Choose and checkout the selected tag
        run: |
          git checkout ${{ github.event.inputs.tag }}
      
      # Add your build/test/deploy steps here
      - name: Example step
        run: echo "Running with tag ${{ github.event.inputs.tag }}"
